plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

base {
    archivesName = rootProject.archives_base_name
}

sourceSets {
    main {
        java.srcDirs = [
            rootProject.file('common/src/main/java'),
            rootProject.file('common/src/client/java'),
            file('src/main/java')
        ]
        resources.srcDirs = [
            rootProject.file('common/src/main/resources'),
            rootProject.file('common/src/client/resources'),
            file('src/main/resources')
        ]
    }
}

loom {
    runs {
        client {
            runDir rootProject.file('run/fabric').absolutePath
        }
    }

    mods {
        'piechart' {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    maven {
        name = 'Elpu7'
        url = 'https://maven.elpu7.dev/releases'
    }
    maven {
        name = 'Terraformers'
        url = 'https://maven.terraformersmc.com/'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    def localElib = rootProject.file("../Elib/fabric/build/libs/elib-${project.elib_version}-fabric.jar")
    implementation localElib.exists()
        ? files(localElib)
        : "dev.elpu7:elib-fabric:${project.elib_version}"

    compileOnly("com.terraformersmc:modmenu:${project.modmenu_version}") {
        transitive = false
    }
}

processResources {
    inputs.property 'version', project.version
    inputs.property 'minecraft_dependency', project.minecraft_dependency
    inputs.property 'loader_dependency', project.loader_dependency
    inputs.property 'elib_version', project.elib_version
    filteringCharset = 'UTF-8'

    filesMatching('fabric.mod.json') {
        expand(
            version: project.version,
            minecraft_dependency: project.minecraft_dependency,
            loader_dependency: project.loader_dependency,
            elib_version: project.elib_version
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}

jar {
    archiveFileName = "${rootProject.archives_base_name}-${project.version}-fabric.jar"
    from(rootProject.file('LICENSE.txt')) {
        rename { "${it}_${rootProject.archives_base_name}" }
    }
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            artifactId = "${rootProject.archives_base_name}-fabric"
            from components.java
        }
    }
}
