plugins {
    id 'base'
}

group = project.maven_group
version = project.mod_version

subprojects {
    group = rootProject.maven_group
    version = rootProject.mod_version

    if (project.hasProperty('custom_build_dir')) {
        layout.buildDirectory.set(file("${project.custom_build_dir}/${project.name}"))
    }
}

tasks.register('buildAll') {
    group = 'build'
    description = 'Builds the Fabric, Quilt, and NeoForge artifacts.'
    dependsOn subprojects.collect { "${it.path}:build" }
}

tasks.named('build') {
    dependsOn tasks.named('buildAll')
}
